# http配置
httpConfig:
  # 设置是否使用代理
  agentIF: false
  # 代理IP
  proxyIP: 60.170.152.46
  # 代理IP端口
  port: 38888
  # 设置是否开启异步爬虫
  asynchronousIF: false
  # 设置是否使用cookie缓存
  cookieIF: true
  cookie: first_visit_datetime_pc=2022-10-15+14:44:41; p_ab_id=9; p_ab_id_2=3; p_ab_d_id=364827051; yuid_b=EmB5MwE; __utmc=235335808; _fbp=fb.1.1665812710778.1635932697; privacy_policy_agreement=5; __utmz=235335808.1665814186.2.2.utmcsr=bing|utmccn=(organic)|utmcmd=organic|utmctr=pivxp; _gcl_au=1.1.1928797190.1665814777; factory-pixiv__zc=3.634a50fe5ecfdd1ad12ffc67.10.0.0.0.; factory-pixiv__zc_store={"cv":null}; _ts_yjad=1665814785618; _ga_1Q464JT0V2=GS1.1.1665814796.1.0.1665814802.0.0.0; PHPSESSID=22695263_Ll5JOVa6WE8nEYTE2OKARqfrqmn3mBC0; device_token=a8bba2e8d26978a2bc04e78bb384d98a; _ga_MZ1NL4PHH0=GS1.1.1665813013.1.1.1665814852.0.0.0; c_type=23; privacy_policy_notification=0; a_type=0; b_type=0; login_ever=yes; __utmv=235335808.|2=login ever=yes=1^3=plan=normal=1^6=user_id=22695263=1^9=p_ab_id=9=1^10=p_ab_id_2=3=1^11=lang=zh=1; p_b_type=1; _gid=GA1.2.1166642130.1667541492; QSI_S_ZN_5hF4My7Ad6VNNAi=v:0:0; __utma=235335808.1464093535.1665812693.1667627074.1667629831.7; tag_view_ranking=0xsDLqCEW6~RTJMXD26Ak~KN7uxuR89w~Lt-oEicbBr~ZNRc-RnkNl~CbkyggmWCV~yTWt5hzG4w~Ie2c51_4Sp~_EOd7bsGyl~BU9SQkS-zU~5oPIfUbtd6~qWFESUmfEs~y8GNntYHsi~jH0uD88V6F~qtVr8SCFs5~eVxus64GZU~3gc3uGrU1V~v3nOtgG77A~engSCj5XFq~K8esoIs2eW~liM64qjhwQ~uusOs0ipBx~CkDjyRo6Vc~5WlN6qpDZj~xha5FQn_XC~jhuUT0OJva~LJo91uBPz4~Hry6GxyqEm~Mf52HwdQ_f~ZPjQtvhTg3~tgP8r-gOe_~UleIdxNJoU~28gdfFXlY7~fg8EOt4owo~1HD6lhXO_A~9PI9msRK8Q~ZKYx1SDf_f~smD4GnkGMk~_pwIgrV8TB~Txs9grkeRc~MM6RXH_rlN~QjJSYNhDSl~ETjPkL0e6r~BSlt10mdnm~Pt9XriSgeT~S0JPQL2nVJ~gVfGX_rH_Y~LVSDGaCAdn~aKhT3n4RHZ~4i9bTBXFoE~pnCQRVigpy~TOd0tpUry5~7yp67ixvIf~uW5495Nhg-~rOnsP2Q5UN~n7YxiukgPF~q1r4Vd8vYK~hZzvvipTPD~65aiw_5Y72~jk9IzfjZ6n~-qIIoc67W5~qKHPDN09e1~zUV1dBrslN~EWR7JDW6jH~MWWoQ-PzdL~zyKU3Q5L4C~ouiK2OKQ-A~M2vKPRxAge~ziiAzr_h04~9Gbahmahac~yREQ8PVGHN~TWrozby2UO~azESOjmQSV~aC55Umcfh1~5G4dw6csD3~z6i8Mevt17~K2XSg2MYXR~bLXLCzGML5~KvAGITxIxH~RNN9CgGExV~9ODMAZ0ebV~PwDMGzD6xn~3mvlXxwzlR~RthHN5LPvq~UnhDA4LpTp~59dAqNEUGJ~_hSAdpN9rx~_GuOetFMMO~LK401HJLtl~moGH48WbdM~8p7FrLtVHU~G6QBo1zPqK~Oa9b6mEc1T~hMU3QbbDfI~9dh32MPwDj~Hj14wy2Hyl~ItydjwXLnX~gpglyfLkWs~4gzX-RNalt~HS63sQi11-; _ga=GA1.2.1464093535.1665812693; _ga_75BBYNYN9J=GS1.1.1667629830.6.1.1667630502.0.0.0
  # 设置是否使用请求伪装
  refererIF: true
  # 伪装请求地址
  referer: https://www.pixiv.net/
  # 设置是否使用UA伪装
  userAgentIF: true
  # user标识符
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.26

# 解析配置
analysisConfig:
  # 爬取资源类型
  type:
    - .jpg
    - .png
    # .tga,.svg,.hdr,.raw
  # Selenium
  seleniumConfig:
    # 驱动路径
    seleniumDrivePath: S:\\exploitation\\edgedriver_win64\\msedgedriver.exe
    # Xpath定位元素
    Xpath: //*[@id="root"]/div[2]/div[2]/div/div[1]/main/section/div[1]/div/figure/div/div[1]/div/a/img

# 下载器配置
downloaderConfig:
  # 资源保存路径
  path: D:/img/爬虫图片/doskoinpo-2960920/a/
  # 设置下载资源类型
  type: png