# http配置
httpConfig:
  # 设置是否使用代理
  agentIF: false
  # 代理IP
  proxyIP: 60.170.152.46
  # 代理IP端口
  port: 38888
  # 设置是否开启异步爬虫
  asynchronousIF: false
  # 设置是否使用cookie缓存
  cookieIF: true
  cookie: cookie
  refererIF: true
  # 伪装请求地址
  referer: https://www.pixiv.net/
  # 设置是否使用UA伪装
  userAgentIF: true
  # user标识符
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.26

# 解析配置
analysisConfig:
  # 爬取资源类型
  type:
    - .jpg
    - .png
    # .tga,.svg,.hdr,.raw
  # Selenium
  seleniumConfig:
    # 驱动路径
    seleniumDrivePath: S:\\exploitation\\edgedriver_win64\\msedgedriver.exe
    # Xpath定位元素
    Xpath: //*[@id="root"]/div[2]/div[2]/div/div[1]/main/section/div[1]/div/figure/div/div[1]/div/a/img

# 下载器配置
downloaderConfig:
  # 资源保存路径
  path: D:/img/爬虫图片/
  # 设置下载资源类型
  type: png
